### ISSUE TITLE
Using valuePublisher completes on first error

### ISSUE THREAD

**Issue by DominikPetho** [GoodRequest/GoodPersistence#7]
**Describe the bug**
In case we are subscribed to valuePublisher, after first error passed to subject, subject completes and is not reinitialized. After error we are unable to receive new values passed to keychain. 
 
**To Reproduce**
1. Create Keychain
2. Subscribe to valuePublisher
3. Try to force error inside keychain property
4. Pass valid value to property
5. New value is not receiver in valuePublisher

**Expected behavior**
After receiving error, I am able to receive next values.

**Additional context**
Suggested solution: 
1. private let newSubject: PassthroughSubject<Either<T, KeychainError>, Never> = PassthroughSubject()
2. private let newSubject: PassthroughSubject<Event<T, KeychainError>, Never> = PassthroughSubject()

**Comment by andrej-jasso** [comment]
We removed error emitting and allowed just value emitting. Also methods to retrieve and save data throw errors which are logged and you can connect on the logger now
